version: '3.8'

services:
  # Single Full-Stack Container
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-fullstack
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/ecommerce
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-jwt-key-change-this
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-email-app-password
      EMAIL_SERVICE: gmail
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
    volumes:
      - app_uploads:/app/backend/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ecommerce-network

volumes:
  mongodb_data:
    driver: local
  app_uploads:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
