services:
  # Single Full-Stack Service
  - type: web
    name: ecommerce-fullstack
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
    healthCheckPath: /api/health

  # MongoDB Database
  - type: pserv
    name: ecommerce-mongodb
    env: docker
    plan: starter
    dockerfilePath: ./mongo.Dockerfile
    dockerContext: .
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false
      - key: MONGO_INITDB_DATABASE
        value: ecommerce
