services:
  # Backend API Service
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
    # Add your environment variables here:
    # - key: MONGODB_URI
    #   sync: false
    # - key: JWT_SECRET
    #   sync: false
    
  # Frontend Static Site
  - type: static
    name: ecommerce-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18
